version: "3.8"

x-airflow-image: &airflow_image apache/airflow:2.7.2-python3.9  

networks:
  airflow:
    driver: bridge

services:
  api:
    build:
      context: ./services/flask
    depends_on:
      - jobsity-postgres
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://jobsity:jobsity@jobsity-postgres:5432/jobsity
    ports:
      - 50555:5000
    volumes:
      - ./services/flask/app:/usr/src/app/app
    restart: always
    networks:
      - airflow

  spark-master:
    build:
      context: ./services/spark
    container_name: spark-master
    ports:
      - "8888:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    networks:
      - airflow

  spark-worker:
    build:
      context: ./services/spark
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - airflow

  jobsity-postgres:
    image: postgis/postgis:14-3.2-alpine
    container_name: jobsity-postgres
    environment:
      - POSTGRES_USER=jobsity
      - POSTGRES_DB=jobsity
      - POSTGRES_PASSWORD=jobsity
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    networks:
      - airflow

  airflow-postgres:
    image: postgres:13.1
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - airflow

  redis:
    image: redis:5.0.5
    container_name: redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 6379:6379
    networks:
      - airflow

  webserver:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    container_name: airflow-webserver
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./airflow_files/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./files:/opt/airflow/files
      - /var/run/docker.sock:/var/run/docker.sock
      - ./spark/app:/usr/local/spark/app
    depends_on:
      - airflow-postgres
      - redis
      - initdb
    command: webserver
    networks:
      - airflow

  flower:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    container_name: airflow-flower
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - redis
    command: celery flower
    networks:
      - airflow

  scheduler:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    container_name: airflow-scheduler
    env_file:
      - .env
    volumes:
      - ./airflow_files/dags:/opt/airflow/dags
    command: scheduler
    depends_on:
      - initdb
    networks:
      - airflow

  worker:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    container_name: airflow-worker
    env_file:
      - .env
    volumes:
      - ./airflow_files/dags:/opt/airflow/dags
    command: celery worker
    depends_on:
      - scheduler
    networks:
      - airflow

  initdb:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    env_file:
      - .env
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com"
    depends_on:
      - redis
      - airflow-postgres
    networks:
      - airflow

  add_connection:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    env_file:
      - .env
    depends_on:
      - initdb
      - webserver
    entrypoint: /bin/bash
    command: -c 'airflow connections add --conn-host spark://spark-master:7077 --conn-type Spark spark_default'
    networks:
      - airflow

  add_hdfs_connection:
    build:
      context: ./services/airflow
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    env_file:
      - .env
    depends_on:
      - initdb
      - webserver
    entrypoint: /bin/bash
    command: -c 'airflow connections add --conn-host hadoop-namenode:8020 --conn-type hdfs hdfs_default'
    networks:
      - airflow

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=datalake
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 8020:8020
    networks:
      - airflow

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    depends_on:
      - hadoop-namenode
    env_file:
      - ./hadoop.env
    networks:
      - airflow

  hadoop-datanode-init:
    build:
      context: ./services/hadoop
    depends_on:
      - hadoop-datanode
    env_file:
      - ./hadoop.env
    networks:
      - airflow